// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Box: typeof import('vue-termui')['TuiBox']
    Br: typeof import('vue-termui')['TuiNewline']
    Download: typeof import('./src/components/download/index.vue')['default']
    Guide: typeof import('./src/components/guide/index.vue')['default']
    Header: typeof import('./src/components/header/index.vue')['default']
    InputWrap: typeof import('./src/components/input/InputWrap.vue')['default']
    Package: typeof import('./src/components/package/index.vue')['default']
    Text: typeof import('vue-termui')['TuiText']
  }
}
